# Generated by Django 5.0.5 on 2024-05-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(db_column='номер', verbose_name='номер')),
                ('address', models.CharField(db_column='адрес', max_length=255, verbose_name='адрес')),
                ('area', models.FloatField(db_column='площадь', verbose_name='площадь в м2')),
                ('price', models.PositiveIntegerField(db_column='стоимость', verbose_name='стоимость')),
                ('description', models.TextField(db_column='описание', verbose_name='описание')),
                ('users', models.ManyToManyField(db_column='понравилось пользователям', to=settings.AUTH_USER_MODEL, verbose_name='пользователи, добавившие в список понравившихся')),
            ],
            options={
                'verbose_name': 'квартира',
                'verbose_name_plural': 'квартиры',
                'db_table': 'квартиры',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='файл', upload_to='photos', verbose_name='фото')),
                ('description', models.CharField(db_column='описание', max_length=255, verbose_name='описание')),
                ('appartment', models.ForeignKey(db_column='квартира', on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
            ],
            options={
                'db_table': 'фото',
            },
        ),
        migrations.AddConstraint(
            model_name='appartment',
            constraint=models.CheckConstraint(check=models.Q(('area__gte', 0.0)), name='area__positive_constraint'),
        ),
    ]
